export type Unit = {
  id: string; title: string; subtitle: string; emoji: string; duration: string;
  prompt: string; level: string; objective: string; part: string; questionType: string;
  bandTarget: string; prepSeconds?: number; responseSeconds?: number; image?: string; imageContext?: string;
};
export type Level = { id: string; name: string; label: string; color: string; progress: number; bandGuide: string; units: Unit[] };
const cue = (title:string, bullets:string[], followup:string) => `${title}\nYou should say:\n${bullets.map(x=>`• ${x}`).join('\n')}\nAnd explain why it was important to you.\n\nFollow-up: ${followup}`;
const part3 = (q:string) => `Let’s discuss this in a more general way. ${q}`;
function makeUnits(level:string, items:[string,string,string][]):Unit[]{
 return items.map(([title,subtitle,prompt],i)=>{
  let part='IELTS-style Part 1 · familiar topics', questionType='Short personal questions', prepSeconds=0, responseSeconds=30;
  if(level==='B1'&&i>=4){part='IELTS-style Part 2 · individual long turn';questionType='Cue card · prepare 1 minute, speak 1–2 minutes';prepSeconds=60;responseSeconds=120;}
  if(level==='B2'&&i>=3){part=i===3?'IELTS-style Part 2 · long turn':'IELTS-style Part 3 · discussion';questionType=i===3?'Cue card · prepare 1 minute, speak 1–2 minutes':'Abstract discussion · explain, compare, speculate';prepSeconds=i===3?60:0;responseSeconds=i===3?120:60;}
  if((level==='C1'||level==='C2')&&i>=2){part='IELTS-style Part 3 · discussion';questionType='Extended discussion · develop and justify ideas';responseSeconds=75;}
  if((level==='C1'||level==='C2')&&i===7){part='Speaking mock · Parts 1–3';questionType='Timed mock interview · 11–14 minutes';prepSeconds=60;responseSeconds=840;}
  let finalPrompt=prompt;
  if(part.includes('Part 2')&&!part.includes('Part 3')&&!part.includes('Speaking mock')&&!prompt.includes('You should say:'))finalPrompt=cue(title,[subtitle,'what happened and who was involved','what you learned or how you felt'],prompt);
  if(part.includes('Part 3'))finalPrompt=part3(prompt);
  const bandTarget=level==='A1'||level==='A2'?'Foundation before IELTS band interpretation':level==='B1'?'Developing · roughly IELTS 4–5 guide':level==='B2'?'Independent · roughly IELTS 5.5–6.5 guide':level==='C1'?'Advanced · roughly IELTS 7–8 guide':'Highly proficient · roughly IELTS 8.5–9 guide';
  return {id:`${level}-U${i+1}`,title,subtitle,prompt:finalPrompt,emoji:['👋','☕','🧭','💬','✈️','🗣️','🧩','✨'][i],duration:part.includes('mock')?'11–14 menit':prepSeconds?'3–5 menit':'3–4 menit',level,objective:subtitle,part,questionType,bandTarget,prepSeconds,responseSeconds};
 });
}
export const curriculum:Level[]=[
 {id:'A1',name:'Beginner',label:'Fondasi speaking',color:'#e7f2e9',progress:0,bandGuide:'Fondasi prates IELTS — IELTS tidak menetapkan padanan band resmi untuk A1.',units:makeUnits('A1',[
  ['Introductions','Memperkenalkan diri dengan kalimat sederhana','What is your name? Where are you from?'],['Home & neighbourhood','Mendeskripsikan rumah dan lingkungan','Do you live in a house or an apartment? Tell me about your neighbourhood.'],['Family & friends','Mendeskripsikan orang terdekat','Tell me about someone in your family.'],['Daily routine','Bercerita singkat tentang rutinitas','What do you usually do in the morning?'],['Likes & hobbies','Menjawab pertanyaan familiar dan memberi alasan sederhana','What do you like doing in your free time?'],['Food & drink','Memesan dan menyebutkan preferensi','What kind of food do you like?'],['Study & work','Berbicara tentang sekolah atau pekerjaan','Do you work or are you a student?'],['A1 speaking checkpoint','Menjawab pertanyaan pendek tentang topik familiar','Let’s talk about your home, daily routine and hobbies.']])},
 {id:'A2',name:'Elementary',label:'Jawaban berkembang',color:'#fff0de',progress:0,bandGuide:'Jembatan ke IELTS-style Speaking Part 1 — bukan konversi skor resmi.',units:makeUnits('A2',[
  ['Describe a market scene','Amati gambar, sebutkan orang, kegiatan, tempat dan detail yang terlihat','Describe what is happening in the picture. What might the people be doing?'],['Travel & transport','Menceritakan perjalanan dan memberi detail','How do you usually travel around your city?'],['Shopping & services','Mengajukan pertanyaan dan menyelesaikan transaksi','Tell me about something useful you bought recently.'],['A memorable day','Menceritakan pengalaman lampau secara runtut','Describe a day you really enjoyed.'],['Plans & invitations','Membicarakan rencana dan alasan','What would you like to do next weekend?'],['Food traditions','Membandingkan kebiasaan makan','What food is popular in your hometown?'],['Weather & seasons','Menjawab pertanyaan topik familiar dengan detail','What kind of weather do you enjoy? Why?'],['A2 Part 1 checkpoint','Memberi jawaban lebih lengkap dengan contoh sederhana','Let’s talk about where you live, food and free time.']])},
 {id:'B1',name:'Intermediate',label:'Mandiri & terstruktur',color:'#e9edff',progress:0,bandGuide:'Pengembangan menuju B1; IELTS sekitar band 4–5 hanya sebagai gambaran kasar.',units:makeUnits('B1',[
  ['Free time & interests','Memperluas jawaban Part 1 dengan alasan dan contoh','How has the way people spend their free time changed?'],['Your hometown','Mendeskripsikan perubahan dan pengalaman','What do you like most about the place where you grew up?'],['Study, work & goals','Menjelaskan pengalaman dan tujuan','What skill would you like to develop for your future career?'],['Technology in daily life','Membandingkan kebiasaan dan memberi opini','How has technology changed the way people communicate?'],['Cue card: a person','Berbicara 1–2 menit dengan struktur awal-tengah-akhir',cue('Describe a person who has influenced you',['who this person is','how you know them','what qualities you admire'], 'How has this person influenced your choices?')],['Cue card: a place','Mengembangkan deskripsi tempat dengan detail sensorik',cue('Describe a place you enjoy visiting',['where it is','when you first went there','what you do there'], 'Why do people need places to relax?')],['Cue card: an experience','Menceritakan pengalaman, perasaan dan hasil',cue('Describe an experience that taught you something',['what happened','who was with you','what you learned'], 'Why do people learn from experience?')],['B1 speaking checkpoint','Menggabungkan Part 1 dan long turn Part 2','Tell me about your interests, then describe a meaningful experience.']])},
 {id:'B2',name:'Upper intermediate',label:'Spontan & analitis',color:'#f5e9ff',progress:0,bandGuide:'B2 sering beririsan dengan IELTS 5.5–6.5; hubungan level dan band tidak satu-banding-satu.',units:makeUnits('B2',[
  ['Work-life balance','Menjawab topik familiar secara spontan','How important is work-life balance in modern society?'],['Travel & culture','Membandingkan pengalaman dan perspektif','How can travel change a person’s understanding of other cultures?'],['Describe a useful skill','Menyampaikan long turn koheren dengan contoh',cue('Describe a practical skill you learned',['what the skill is','how you learned it','how long it took'], 'Should practical skills be taught at school?')],['Education & opportunity','Menghubungkan topik Part 2 ke isu yang lebih umum',part3('How has access to education changed in recent decades?')],['Technology & society','Membandingkan manfaat, risiko dan dampak','Do the benefits of social media outweigh its disadvantages?'],['Cities & communities','Berspekulasi tentang perubahan sosial','What makes a city a good place for young people to live?'],['Environment & choices','Mengembangkan argumen dengan sebab-akibat','How much responsibility should individuals take for protecting the environment?'],['B2 speaking checkpoint','Simulasi Part 1, Part 2 dan diskusi Part 3','Let’s discuss a skill you learned and the role of education in society.']])},
 {id:'C1',name:'Advanced',label:'Mahir profesional',color:'#e3f4f3',progress:0,bandGuide:'C1 umumnya beririsan sekitar IELTS 7–8; band AI adalah estimasi latihan, bukan hasil resmi.',units:makeUnits('C1',[
  ['Nuanced opinions','Mengutarakan opini dengan kualifikasi dan contoh','To what extent should governments influence people’s lifestyle choices?'],['Describe a turning point','Mengelola long turn secara natural dan detail',cue('Describe a decision that had a significant impact on your life',['what the decision was','what options you considered','what happened as a result'], 'Why do people sometimes find important decisions difficult?')],['Innovation & responsibility','Menimbang trade-off dalam diskusi abstrak',part3('Who should be responsible when new technology causes social harm?')],['Culture & identity','Menyampaikan nuansa dan perspektif berbeda','How does globalisation affect local culture?'],['Workplace communication','Memberi feedback diplomatis dan presisi','How can organisations encourage people to share different opinions?'],['Public policy','Membangun argumen yang seimbang','Should cities prioritise public transport over private cars?'],['Uncertainty & evidence','Menyatakan batas bukti dan tingkat kepastian','How should people make decisions when reliable information is limited?'],['C1 full speaking mock','Simulasi Speaking IELTS-style 11–14 menit, tiga bagian','Begin with familiar questions, continue with a cue card, then explore broader issues.']])},
 {id:'C2',name:'Proficient',label:'Presisi & fleksibel',color:'#fff0f0',progress:0,bandGuide:'C2 dapat beririsan sekitar IELTS 8.5–9; bukan ekuivalensi otomatis atau sertifikasi.',units:makeUnits('C2',[
  ['Spontaneous Part 1','Menjawab topik familier secara ringkas namun bernuansa','How have your interests changed over the years?'],['Long turn with nuance','Mengembangkan ide abstrak dengan koherensi dan detail',cue('Describe an idea that changed the way you see the world',['what the idea was','where you encountered it','how it challenged your assumptions'], 'Why are people sometimes reluctant to reconsider their beliefs?')],['Ethics & technology','Menganalisis implikasi dan keberatan yang masuk akal',part3('Can innovation be considered progress if it increases inequality?')],['Education & society','Menyintesis perspektif berbeda','What should education prepare people for in a rapidly changing world?'],['Language & identity','Membahas makna, konteks dan implikatur','Can a language influence the way people think?'],['Leadership & disagreement','Merespons tantangan tanpa kehilangan arah','How should leaders respond when experts strongly disagree?'],['Abstract discussion','Membangun jawaban spontan dengan ketepatan leksikal','Is certainty always desirable when making important decisions?'],['C2 full speaking mock','Simulasi tiga bagian dan refleksi mandiri','Complete an IELTS-style interview with sustained, flexible responses.']])}
];
const marketPicture=curriculum.find(level=>level.id==='A2')!.units[0];
marketPicture.image='/learnenglish/images/speaking/market-conversation-scene-flow.jpg';
marketPicture.imageContext='In the visible illustration, a market vendor hands a paper bag of oranges to a customer; another shopper compares tomatoes; a parent stands with a child; stalls display vegetables and flowers. Only treat these as visible details; any motives or background story are learner inferences, not facts.';
marketPicture.part='Visual conversation enrichment · not an official IELTS Speaking task';
marketPicture.questionType='Picture description · observe, describe, infer';
marketPicture.bandTarget='A2 vocabulary and speaking practice';
export const allUnits=curriculum.flatMap(level=>level.units);
// Use only individually reviewed assets. Video lessons stay empty until an editor verifies a short, relevant source and its questions.
export const videoLessons: {id:string;title:string;youtubeId:string;source:string;durationSeconds:number;questions:string[]}[]=[];
export const initialData={completed:[] as string[],listeningCompleted:[] as string[],xp:0,streak:1,sessions:[] as any[],settings:{model:'clario/gemini-3.7-flash',baseUrl:'https://clariohub.id/v1',tts:'native',voice:'',saveAudio:false}};
