export type ListeningQuestion={prompt:string;options:string[];answer:number;explain:string};
export type ListeningLesson={id:string;level:string;title:string;objective:string;script:string;questions:ListeningQuestion[];image?:string};
const lesson=(id:string,level:string,title:string,objective:string,script:string,questions:ListeningQuestion[]):ListeningLesson=>({id,level,title,objective,script,questions});
export const listeningLessons:ListeningLesson[]=[
lesson('L-A1-01','A1','A new neighbour','Identify names, places, and simple details.','Hello, I’m Maya. I moved into apartment 4B on Monday. The building is next to the small green park. I work at a bakery, so I leave home at six in the morning.',[
{prompt:'Which apartment does Maya live in?',options:['Apartment 4B','Apartment 6A','Apartment 14'],answer:0,explain:'She says, “I moved into apartment 4B.”'},{prompt:'Where is the building?',options:['Behind a station','Next to a small park','Across from a bakery'],answer:1,explain:'The building is next to the green park.'}]),
lesson('L-A1-02','A1','At the café','Understand a short order and its price.','Good morning. Can I have one cheese sandwich and a cup of tea, please? Certainly. The sandwich is four pounds and the tea is two pounds. Here is your order. You can sit by the window.',[
{prompt:'What drink does the customer order?',options:['Coffee','Orange juice','Tea'],answer:2,explain:'The customer asks for a cup of tea.'},{prompt:'How much is the whole order?',options:['Four pounds','Six pounds','Eight pounds'],answer:1,explain:'Four pounds plus two pounds equals six pounds.'}]),
lesson('L-A1-03','A1','The morning bus','Follow a simple timetable.','The number twelve bus leaves the library at eight fifteen. It stops at the hospital at eight thirty and reaches the sports centre at eight forty-five. On Saturdays, the first bus leaves thirty minutes later.',[
{prompt:'What time does the bus reach the hospital on a normal day?',options:['8:15','8:30','8:45'],answer:1,explain:'The hospital stop is at eight thirty.'},{prompt:'What time does the first Saturday bus leave?',options:['8:15','8:30','8:45'],answer:2,explain:'It leaves 30 minutes later than 8:15, so it leaves at 8:45.'}]),
lesson('L-A2-01','A2','A weekend plan','Identify a change of plan and the reason.','Hi, Lina. Are we still going to the beach on Sunday? I checked the weather, and it will rain all afternoon. Let’s visit the science museum instead. It opens at ten, and students can get a discounted ticket if they bring their ID.',[
{prompt:'Why do they change the plan?',options:['The beach is closed','Rain is expected','The museum is free'],answer:1,explain:'The forecast says it will rain all afternoon.'},{prompt:'What should students bring?',options:['A library card','A student ID','A raincoat'],answer:1,explain:'They need their ID to get the discounted ticket.'}]),
lesson('L-A2-02','A2','A message from the hotel','Understand directions and check-in details.','Welcome to Greenway Hotel. Your room is ready after two o’clock. Breakfast is served from seven until half past nine in the garden room. To reach the old town, walk to the end of this street and turn left at the pharmacy.',[
{prompt:'When can the guest enter the room?',options:['After 1:30','After 2:00','After 2:30'],answer:1,explain:'Check-in is after two o’clock.'},{prompt:'Where is breakfast served?',options:['In the garden room','In the lobby','At the pharmacy'],answer:0,explain:'Breakfast is in the garden room.'}]),
lesson('L-A2-03','A2','Returning a jacket','Track a shop conversation.','I bought this jacket yesterday, but the zip is broken. Do you still have the receipt? Yes, here it is. Would you like a replacement or a refund? A replacement, please, but in a larger size. I can order one for Friday.',[
{prompt:'What is wrong with the jacket?',options:['The zip is broken','The sleeves are too short','The colour is different'],answer:0,explain:'The customer says the zip is broken.'},{prompt:'When will the replacement arrive?',options:['Thursday','Friday','Saturday'],answer:1,explain:'The shop assistant says it can be ordered for Friday.'}]),
lesson('L-B1-01','B1','A community garden','Recognise main ideas and supporting details.','Our community garden began three years ago on an empty piece of land behind the library. At first, only six families took part. Now more than forty people grow vegetables there. The most popular activity is the Saturday workshop, where experienced gardeners teach beginners. We used to sell all the produce, but this year we donate one third to a local food bank.',[
{prompt:'How many families joined at the beginning?',options:['Six','Fourteen','Forty'],answer:0,explain:'The speaker says only six families took part at first.'},{prompt:'What happens to one third of this year’s produce?',options:['It is sold at the library','It is donated to a food bank','It is used in workshops'],answer:1,explain:'One third is donated to a local food bank.'}]),
lesson('L-B1-02','B1','A delayed train','Follow a sequence and practical instructions.','Attention, please. The 16:20 service to Northbridge is delayed by approximately twenty minutes because of a signal problem. Passengers travelling to Westport should take the 16:35 train from platform six and change at Central. Your tickets will be accepted on that service.',[
{prompt:'What caused the delay?',options:['A signal problem','Heavy rain','A staff shortage'],answer:0,explain:'The announcement mentions a signal problem.'},{prompt:'What should Westport passengers do?',options:['Wait for platform six to reopen','Take the 16:35 train and change at Central','Buy a new ticket'],answer:1,explain:'They should take the 16:35 service and change at Central.'}]),
lesson('L-B1-03','B1','Choosing a short course','Compare options and identify a recommendation.','I looked at two evening courses. The photography class meets twice a week and costs more, but it includes equipment. The design course is cheaper and meets on Wednesdays only. Since I already have a camera and work late on Tuesdays, I think the design course suits me better, even though it runs for an extra month.',[
{prompt:'Why is the photography course less suitable?',options:['It has no equipment','It meets on a Tuesday when the speaker works late','It lasts an extra month'],answer:1,explain:'The speaker works late on Tuesdays.'},{prompt:'Which course does the speaker prefer?',options:['Photography','Design','Neither course'],answer:1,explain:'They conclude the design course suits them better.'}]),
lesson('L-B2-01','B2','A university project','Distinguish the initial plan from the final decision.','We originally planned to survey local residents about cycling. After the first week, we realised that response rates were low, particularly among older residents. Rather than extend the deadline, we partnered with two community centres and offered paper copies alongside the online form. This improved participation, although it meant our results arrived later than expected. The final report will therefore focus on access to cycling facilities, not on travel habits in general.',[
{prompt:'What change helped improve participation?',options:['Extending the deadline','Offering paper surveys through community centres','Removing older residents from the sample'],answer:1,explain:'Paper copies at two community centres improved participation.'},{prompt:'What will the final report focus on?',options:['Access to cycling facilities','Travel habits in general','The cost of public transport'],answer:0,explain:'The report narrows its focus to access to cycling facilities.'}]),
lesson('L-B2-02','B2','A museum audio guide','Infer the speaker’s view and follow contrast.','The audio guide was designed to make the exhibition accessible without overwhelming visitors with dates. We tested two versions: one with detailed historical narration and another built around short personal stories. Visitors spent longer at the exhibits when listening to the second version, but some specialists felt it omitted useful context. We are keeping the story-based approach while adding optional layers for those who want more detail.',[
{prompt:'What did the test suggest about the story-based version?',options:['Visitors spent longer with exhibits','It was difficult for visitors to hear','Specialists preferred it unanimously'],answer:0,explain:'Visitors spent longer at exhibits with the short personal stories.'},{prompt:'What is the planned improvement?',options:['Remove all narration','Add optional detailed information','Replace stories with dates'],answer:1,explain:'Optional layers will provide more context.'}]),
lesson('L-B2-03','B2','A workplace briefing','Identify a qualification and a deadline.','Before we launch the new booking system, please check your team’s rota by Thursday afternoon. The system itself goes live on Monday, not Friday as stated in the first email. Managers should report any staffing gaps to Priya, while technical problems should go directly to the help desk. We are not changing the current holiday approval process during this launch.',[
{prompt:'When does the system go live?',options:['Thursday','Friday','Monday'],answer:2,explain:'The corrected date is Monday.'},{prompt:'Who should receive reports about staffing gaps?',options:['Priya','The help desk','The system vendor'],answer:0,explain:'Managers should report staffing gaps to Priya.'}]),
lesson('L-C1-01','C1','Public transport and city access','Track an argument, concession, and conclusion.','When cities debate transport policy, investment is often framed as a choice between expanding roads and improving public transit. That contrast is too simple. Even well-funded transit networks cannot serve every trip, particularly in low-density districts. Yet adding road capacity tends to attract additional car journeys, so congestion frequently returns. A more durable strategy combines reliable buses, safe walking routes, and targeted road improvements. The critical measure is not the speed of any single mode, but whether residents can reach essential services without excessive cost or delay.',[
{prompt:'Why does the speaker call the usual debate too simple?',options:['Transit cannot serve every trip, while road expansion can attract more traffic','Roads are never used by residents','Cities have already removed all buses'],answer:0,explain:'The speaker presents limits on both transit and road expansion.'},{prompt:'What should be the critical measure?',options:['The speed of cars alone','Access to essential services at reasonable cost and time','The number of new roads'],answer:1,explain:'The conclusion prioritises practical access to essential services.'}]),
lesson('L-C1-02','C1','How museums use digital media','Separate evidence from a cautious claim.','Digital interpretation is sometimes promoted as a way to make museums universally accessible. The evidence is more qualified. In a recent visitor study, audio descriptions helped people with low vision navigate one gallery, but the benefit depended on clear wayfinding and staff support. Interactive screens also increased dwell time, though longer visits did not necessarily indicate deeper learning. We should therefore treat technology as one component of inclusive design, rather than as a substitute for thoughtful exhibition planning.',[
{prompt:'What qualification is made about interactive screens?',options:['They always improve learning','Longer visits do not automatically prove deeper learning','They are only useful in outdoor galleries'],answer:1,explain:'The speaker cautions that dwell time is not the same as learning.'},{prompt:'What role should technology play?',options:['Replace exhibition planning','Be one part of inclusive design','Be removed from museums'],answer:1,explain:'Technology is framed as one component, not a substitute.'}]),
lesson('L-C1-03','C1','A research seminar','Follow methodological nuance.','The study’s headline finding suggests that flexible working improves retention. I would be careful about treating that relationship as causal. Employees who were already more satisfied may have been more likely to select flexible roles, and the sample excluded several small firms. The authors partially address this by comparing workers before and after a policy change, but the observation period is only six months. The result is promising, therefore, but it should guide a larger longitudinal study rather than immediate universal adoption.',[
{prompt:'Why is a causal interpretation uncertain?',options:['The study had no participants','Selection effects and a limited sample may influence the relationship','The policy lasted ten years'],answer:1,explain:'Satisfied employees may self-select; small firms were excluded.'},{prompt:'What does the speaker recommend?',options:['Adopt the policy everywhere immediately','Ignore the study','Conduct a larger longitudinal study'],answer:2,explain:'The finding should inform a larger longitudinal study.'}]),
lesson('L-C2-01','C2','The language of risk','Interpret a sophisticated distinction.','Risk communication is often treated as a problem of translating statistics into simpler language. Clarity matters, but comprehension is not merely a property of the message. It also depends on the audience’s prior knowledge, institutional trust, and the consequences people attach to uncertainty. A perfectly accurate probability can still mislead if listeners assume it applies to an individual case. Effective communication therefore makes the reference class explicit, explains what is unknown, and gives people a usable basis for action without pretending uncertainty has disappeared.',[
{prompt:'What does the speaker argue about comprehension?',options:['It depends only on simpler wording','It also depends on audience knowledge, trust, and context','Statistics should never be used'],answer:1,explain:'Comprehension depends on more than wording.'},{prompt:'Why should a reference class be explicit?',options:['So listeners do not mistake a general probability for an individual prediction','To make the statistic appear more certain','To avoid explaining unknowns'],answer:0,explain:'The speaker warns against assuming a population probability applies to one person.'}]),
lesson('L-C2-02','C2','Rethinking a historical archive','Follow a counterargument and synthesis.','Digitising an archive can appear to democratise access, yet the phrase conceals two separate questions: who can retrieve the material, and whose histories were preserved in the first place. Search tools may broaden discovery while reproducing cataloguing categories inherited from earlier institutions. This does not make digitisation futile. It does mean that access initiatives should be paired with transparent metadata, community-led description, and a willingness to record disagreement. An archive becomes more open not simply when more files are online, but when the conditions shaping their interpretation can also be examined.',[
{prompt:'What two questions are distinguished?',options:['Who can retrieve material and whose histories were preserved','Which files are oldest and which are largest','How much digitisation costs and who pays'],answer:0,explain:'Access and historical selection are separate issues.'},{prompt:'What makes an archive more open, according to the speaker?',options:['Putting every file online without context','Making interpretive conditions examinable as well as providing access','Using only one official description'],answer:1,explain:'The conclusion emphasises examining how material is interpreted.'}]),
lesson('L-C2-03','C2','A lecture on scientific models','Recognise a refined distinction between prediction and explanation.','A model can predict accurately without explaining the mechanism that produces the outcome. That distinction is not a defect in every context: a forecasting tool may be valuable when decisions are time-sensitive and its errors are well characterised. The difficulty arises when predictive success is taken as evidence that the model captures causal structure. In this project, we use prediction to identify patterns, then test a smaller set of mechanistic hypotheses against independent observations. The two approaches are complementary, but their evidential claims should not be conflated.',[
{prompt:'When may a predictive model be useful without explaining a mechanism?',options:['When a decision is time-sensitive and errors are understood','Only when it proves causation','Never'],answer:0,explain:'The speaker accepts forecasting use when errors are well characterised.'},{prompt:'What warning closes the lecture?',options:['Prediction and explanation should not be treated as the same claim','All models should be replaced','Independent observations are unnecessary'],answer:0,explain:'The speaker says the evidential claims should not be conflated.'}]),
];

const lessonIllustrations:Record<string,string>={
 'L-A1-02':'/learnenglish/images/listening/a1-cafe-order.jpg',
 'L-A1-03':'/learnenglish/images/listening/a1-morning-bus-stop.jpg',
 'L-A2-01':'/learnenglish/images/listening/a2-weekend-museum-plan.jpg',
 'L-B1-01':'/learnenglish/images/listening/b1-community-garden.jpg',
 'L-B2-01':'/learnenglish/images/listening/b2-university-fieldwork.jpg',
 'L-C1-01':'/learnenglish/images/listening/c1-city-transport-options.jpg',
 'L-C2-02':'/learnenglish/images/listening/c2-community-archive.jpg',
};
for(const item of listeningLessons){if(lessonIllustrations[item.id])item.image=lessonIllustrations[item.id];}
