import {useMemo,useState} from 'react';
import {Check,Headphones,Play,RotateCcw,Volume2} from 'lucide-react';
import {toast} from 'sonner';
import {listeningLessons, type ListeningLesson} from './listening';
import type {AppData} from './storage';

export default function ListeningPage({data,setData}: {data:AppData;setData:(fn:(p:AppData)=>AppData)=>void}){
 const [level,setLevel]=useState('All');const [activeId,setActiveId]=useState(listeningLessons[0].id);const [answers,setAnswers]=useState<Record<string,number>>({});const [checked,setChecked]=useState<Record<string,boolean>>({});const [showScript,setShowScript]=useState(false);
 const levels=['All','A1','A2','B1','B2','C1','C2'];const lessons=useMemo(()=>listeningLessons.filter(x=>level==='All'||x.level===level),[level]);const active=listeningLessons.find(x=>x.id===activeId)||lessons[0]||listeningLessons[0];const done=(data.listeningCompleted||[]) as string[];const score=active.questions.reduce((n,q,i)=>n+(checked[`${active.id}:${i}`]&&answers[`${active.id}:${i}`]===q.answer?1:0),0);
 function play(){if(!('speechSynthesis'in window)){toast.error('Text-to-speech tidak tersedia. Gunakan naskah tertulis.');setShowScript(true);return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(active.script);utterance.lang='en-US';utterance.rate=active.level==='A1'||active.level==='A2'?.82:.94;const voice=window.speechSynthesis.getVoices().find(v=>v.lang.toLowerCase().startsWith('en'));if(voice)utterance.voice=voice;window.speechSynthesis.speak(utterance);}
 function check(i:number){const key=`${active.id}:${i}`;if(answers[key]===undefined){toast.info('Pilih satu jawaban lebih dahulu.');return;}setChecked(v=>({...v,[key]:true}));const q=active.questions[i];if(answers[key]===q.answer){toast.success('Benar!');}else toast.message('Belum tepat — baca penjelasan dan coba lagi.');}
 function complete(){const answered=active.questions.every((_,i)=>checked[`${active.id}:${i}`]);if(!answered){toast.info('Periksa semua jawaban sebelum menyelesaikan lesson.');return;}if(!done.includes(active.id)){setData((p:any)=>({...p,listeningCompleted:[...(p.listeningCompleted||[]),active.id],xp:p.xp+10}));toast.success('Listening lesson selesai · +10 XP');}}
 return <div className="listening-page">
  <div className="eyebrow"><Headphones size={15}/> FIXED-SCRIPT LISTENING</div><h1>Listening practice <span>🎧</span></h1><p className="page-intro">Latihan audio dengan naskah orisinal dan pemeriksaan jawaban deterministik. Tidak ada AI yang membuat dialog atau menilai jawaban.</p>
  <div className="listening-notice"><b>Audio & privasi</b><span>Tombol dengar memakai speech synthesis yang tersedia di browser/perangkatmu; ketersediaan suara dan pemrosesan offline bergantung pada OS/browser. Tidak ada unggahan audio atau speech recognition. Naskah dapat dibuka sebagai alternatif aksesibel.</span></div>
  <div className="listening-layout"><aside className="listening-catalog"><div className="level-filters">{levels.map(x=><button key={x} className={level===x?'selected':''} onClick={()=>{setLevel(x);const first=listeningLessons.find(l=>x==='All'||l.level===x);if(first)setActiveId(first.id);}}>{x}</button>)}</div><div className="listening-count">{done.length} / {listeningLessons.length} lesson selesai</div><div className="listening-list">{lessons.map(l=><button key={l.id} className={`listening-item ${l.id===active.id?'active':''}`} onClick={()=>{setActiveId(l.id);setShowScript(false);}}><span className="listen-level">{l.level}</span><span><b>{l.title}</b><small>{l.objective}</small></span>{done.includes(l.id)&&<Check size={16}/>}</button>)}</div></aside>
  <article className="listening-lesson"><div className="lesson-heading"><span className="level-pill">{active.level} · LISTENING</span><h2>{active.title}</h2><p>{active.objective}</p></div>{active.image&&<figure className="listening-visual"><img src={active.image} alt={`Supplementary illustration for ${active.title}`}/><figcaption>Supplementary illustration · answers are based on the audio script.</figcaption></figure>}<div className="audio-player-card"><div className="audio-disc"><Headphones size={25}/></div><div><b>Scripted listening · {active.level}</b><small>Browser speech synthesis · original authored script</small></div><button className="btn-primary" onClick={play}><Play size={16} fill="currentColor"/> Play audio</button></div><button className="text-button script-toggle" onClick={()=>setShowScript(s=>!s)}>{showScript?'Hide transcript':'Show transcript'}</button>{showScript&&<div className="listening-script">{active.script}</div>}
   <div className="listening-questions"><div className="eyebrow">COMPREHENSION CHECK</div>{active.questions.map((q,i)=>{const key=`${active.id}:${i}`;const isChecked=checked[key];const correct=answers[key]===q.answer;return <section className="listening-question" key={key}><h3>{i+1}. {q.prompt}</h3><div className="answer-options">{q.options.map((o,j)=><button key={o} disabled={!!isChecked&&correct} className={`${answers[key]===j?'chosen':''} ${isChecked&&j===q.answer?'right':''} ${isChecked&&answers[key]===j&&!correct?'wrong':''}`} onClick={()=>setAnswers(v=>({...v,[key]:j}))}><span>{String.fromCharCode(65+j)}</span>{o}</button>)}</div>{!isChecked?<button className="outline-btn check-answer" onClick={()=>check(i)}>Check answer</button>:<div className={`answer-feedback ${correct?'correct':'incorrect'}`}><b>{correct?'Correct':'Review this one'}</b><span>{q.explain}</span>{!correct&&<button className="text-button" onClick={()=>setChecked(v=>({...v,[key]:false}))}>Try another answer</button>}</div>}</section>;})}</div><div className="lesson-end"><div><b>Score so far: {score} / {active.questions.filter((_,i)=>checked[`${active.id}:${i}`]).length||0}</b><small>Try as many times as you like; only the final checked answer counts for lesson score.</small></div><button className="btn-primary" disabled={done.includes(active.id)} onClick={complete}>{done.includes(active.id)?'Lesson completed':<>Complete lesson <Check size={15}/></>}</button></div><div className="listening-caveat"><Volume2 size={15}/> Original practice material. It is not an official IELTS Listening test and does not produce an IELTS band score.</div>
  </article></div>
 </div>;
}
